### ISSUE TITLE
have wled installed on D1

### ISSUE THREAD

**Issue by critterskins** [cp2004/OctoPrint-WLED#109]
I have a d1 mini setup with no password or username on my local network.
I also have Wled integration installed on Octoprint nut in the settings where I choose the IP address and test connection it fails. 
not sure what settings to try. Any help will be appreciated thank you.

**Comment by cp2004** [comment]
Please upload the octoprint.log file

**Comment by critterskins** [comment]
octoprint.plugins.wled.api - ERROR - Error connecting to WLED at 192.168.1.56
2021-09-11 21:12:01,028 -

**Comment by cp2004** [comment]
That's not the log file, please upload the whole thing

**Comment by critterskins** [comment]
I'm sorry I figured it out. I'm running multiple access points and had a DHCP conflict as soon as I ran ethernet  to OctoPrint it connected without issue.

**Comment by cp2004** [comment]
Great to see this was solved - seems I forgot to close it.
