### ISSUE TITLE
[Feature Request] Control without WiFi

### ISSUE THREAD

**Issue by notrub** [cp2004/OctoPrint-WLED#126]
My OctoPrint instance is running on a Pi over ethernet.  There is not WiFi available in my project.

If the WLED controller (ESP8266) could be controlled over its GPIO pins or USB port from the Pi's GPIO pins or USB port respectively.

I don't have a particularly convincing reason why this is where you should spend your time, as I am probably a niche case.
Thank you for your work on the rest of this, it is awesome.

**Comment by cp2004** [comment]
Since control through GPIO is not possible with WLED, I'm closing this issue - the offline version is available as WS281x LED Status, connected directly to the Pi.
