### ISSUE TITLE
[Docs] Create some documentation for the configuration & usage of the plugin

### ISSUE THREAD

**Issue by cp2004** [cp2004/OctoPrint-WLED#20]
Doesn't have to be much, but I think there should be some explanations - the settings interface is not the clearest for what everything means.

**Comment by MrTechGadget** [comment]
@cp2004 Charlie, I was following this recently and installed this after it was added to the plugin store.
I am happy to assist with documentation but I think I need a nudge in the right direction or an example config to look at to get started.
I was a little surprised that there didn't seem to be any default configuration upon install even though some items were "enabled" by default.

It looks like in addition to being enabled, I have to add configurations. For the printing effects it made sense, but for the progress effects I'm not sure what needs to be configured (10% done, 25%, etc...)

**Comment by cp2004** [comment]
> I was a little surprised that there didn't seem to be any default configuration upon install even though some items were "enabled" by default.

Yeah, I had a long 'think' about this one. I could not think initially of what default settings to add, so I didn't add any. And the way OctoPrint works with default settings that are lists, it is not easy to make sure all the config stays the same. But yeah, I agree it is not the most user-friendly interface to look at until you understand it. That said, I would really appreciate something from someone who didn't create the thing, to make it clearer.

> for the progress effects I'm not sure what needs to be configured (10% done, 25%, etc...)

In the progress effect case, it is just a single 'config' for each segment - it will display a progress bar, instead of a user-selectable effect as in the 'Printing effects' section, with the configured colours.

---

In terms of docs, initially some markdown files in a `/docs` folder may be enough for something to reference. I was considering running it on [Docusaurus](https://docusaurus.io/), mostly because I like the name but that will take more work to setup, so I will look at it in the future.

Or, if you want to some extra text in the settings UI to explain some of the sections may be more useful, as people will actually read it. A sentence or two above the table here:
![image](https://user-images.githubusercontent.com/31997505/115445217-79670000-a20d-11eb-9391-f74b9f583a2b.png)

May be enough. The templates are a bit spaghetti still, but that would probably go at the top of this file: https://github.com/cp2004/OctoPrint-WLED/blob/main/octoprint_wled/templates/settings/progress.jinja2#L2

**Comment by cp2004** [comment]
Hopefully that helps - of course, just ask more questions if you want 😄

**Comment by MrTechGadget** [comment]
Thanks, this does help enough to get started and I have been testing some different settings over the past few days.

I really do think it would be good to start with a default for segment 0 for a couple settings. A default WLED install will give you a single segment so for a lot of people it would give them a working setup on install after setting the IP/Host of the WLED. Since progress doesn't seem that configurable anyway (my color choice doesn't seem to make a difference) that alone would be good.

As a new user, I think it is easier figure out how to tweak something already in place than to be given a blank slate. You could have a default configuration but leave most or even all as not enabled, then the user would just have to enable the effects they want to use. (and tweak if they want)

**Comment by cp2004** [comment]
I will create a default configuration for segment 0, it does make sense.

> Since progress doesn't seem that configurable anyway (my color choice doesn't seem to make a difference)

Does this mean that there is a bug 👀?

**Comment by cp2004** [comment]
A basic default configuration and some additional explainers are implemented ready for 0.2.0.

**Comment by cp2004** [comment]
@MrTechGadget There's a release candidate available for 0.2.0rc1 if you want to give it a go. Feedback ticket #54.

**Comment by MrTechGadget** [comment]
Awesome, I’ll update and try it out. Been enjoying this plugin constantly!

**Comment by cp2004** [comment]
0.2.0 has been released.
