### ISSUE TITLE
WLED vs OctoPrint WS281x LED Status

### ISSUE THREAD

**Issue by CobaltEcho** [cp2004/OctoPrint-WLED#21]
Both these plugins are made by you, what is the difference between them?

**Comment by cp2004** [comment]
WLED is software you can flash to an ESP device, such as ESP8266 or ESP32, which allows for wireless control of the LEDs from other devices through a web UI, like OctoPrint is for 3D Printers. https://github.com/Aircoookie/WLED 

This plugin allows OctoPrint to connect to a WLED device and send commands to the LEDs wirelessly.

What does WS281x LED Status do? That plugin is for the LEDs to be connected directly to a Raspberry Pi GPIO. It currently had many more features but I plan to bring some similar things to here.

Hopefully that makes sense!

**Comment by tgv26** [comment]
Bonjour ou trouver un schéma pour connecter la bande Neopixel avec le raspberry ?

**Comment by cp2004** [comment]
@tgv26 For this plugin, first you must setup WLED: https://github.com/Aircoookie/WLED

Then it is wireless to OctoPrint, using the settings in the plugin.

If you don't have WLED or anything to set it up on, then you can use WS281x LED Status to connect LEDs directly to the Raspberry Pi.

**Comment by cp2004** [comment]
@CobaltEcho hopefully that made sense, going to close this one as answered now.
