### ISSUE TITLE
[Feature Request] Implement state 'Operational'

### ISSUE THREAD

**Issue by SVLoneStar** [cp2004/OctoPrint-WLED#22]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to show the state 'Operational' via the plugin.

**Describe the solution you'd like**

After state 'Disconnected' (which is represented correctly with the plugin), the state shortly goes to 'Connected' (correctly represented with the plugin) and then to 'Operational'. As this last state can not be configured in the plugin, WLED LEDs turn to black.

**Why should this be implemented?**

I think it would be good to be able to show all states. Just for the sake of completeness. ;-)

**Additional context**

**Comment by cp2004** [comment]
To clarify, to make sure I understand correctly:

* You connect the printer
* The LEDs run the 'connected' event
* After this, they turn black?

This sounds more like a bug or misconfiguration to me - all the effects are event-based, so they shouldn't ever *stop* unless something else is coming to take its place.

**Comment by SVLoneStar** [comment]
Hi Charlie,

it's exactly as you describe it.

First I thought I did a mistake in cofiguring your plugin.

But as other states were represented correctly, I 'guessed' that the LEDs being off in the 'Operational' state are related to a non-covered OctoPrint status.

To rule out a 'complex misconfiguration', I disabled all other configs in your plugin and just left the 'Idle' state enabled. Same result.

 

However...just to make sure, I just again deleted (and not just disabled) the 'Idle' config and re-configured it - and now everything is working as expected.

Very strange...however, thanks a lot for your very helpful plugin!!

 

Best Regards,

Stefan

 

 

 
 

Gesendet: Sonntag, 18. April 2021 um 23:34 Uhr
Von: "Charlie Powell" ***@***.***>
An: "cp2004/OctoPrint-WLED" ***@***.***>
Cc: "SVLoneStar" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [cp2004/OctoPrint-WLED] [Feature Request] Implement state 'Operational' (#22)


 

To clarify, to make sure I understand correctly:


	You connect the printer
	The LEDs run the 'connected' event
	After this, they turn black?


This sounds more like a bug or misconfiguration to me - all the effects are event-based, so they shouldn't ever stop unless something else is coming to take its place.

**Comment by cp2004** [comment]
I will keep an eye on it incase it is a bug, great that it now works.

**Comment by cbrherms** [comment]
@cp2004 I have ended up noticing this one myself recently with the LEDs going to black and overriding other things.
Believe it was related to having `@WLED ON` and `@WLED OFF` as part of my PSU Control action. This seemed to cause some funky issues with it no longer paying attention to the `connected` state. 
I think i might have sorted it now (but I haven't been able to pinpoint just what change fixed it). If I encounter it again i'll open a fresh issue.
