### ISSUE TITLE
does this work with WLED 0.13?

### ISSUE THREAD

**Issue by BootsSiR** [cp2004/OctoPrint-WLED#269]
Installed and when I run a print my LEDs go solid green but never any progress....

**Comment by cp2004** [comment]
As far as I know it works. I suspect it is more likely a slight misconfiguration when adding the effects.

**Comment by BootsSiR** [comment]
ok, just wanted to make sure before I messed around trying to figure it out.  I pretty much installed it, pointed it at WLED and then started a print.  It looked like it was configured ok out of the box for progress... it did change my LEDs a few times when the print started and ended but just to solid colors.
