### ISSUE TITLE
Get back to Idle after Print done. an other Request

### ISSUE THREAD

**Issue by DuschdrBabbe** [cp2004/OctoPrint-WLED#27]
Hi,
at first, super cool plugin i like it!
But after the print is done the idle state doesent come up again.
It keeps the printing state or progress state.

So it is possible to set an time für alerting, like if error/success, then blink red for 5 seconds and get back to the previus state?
A timer would also be great. 5 hours idle = lights off

greetings from germany

Pascal

**Comment by cp2004** [comment]
I have this feature in [WS281x LED Status](https://github.com/cp2004/OctoPrint-WS281x_LED_Status) already, it is on the list to bring across at some point.

**Comment by cp2004** [comment]
As of the above commit, this has been implemented ready for 0.2.0. Look out for a release candidate in the coming days, I'll post about it here.

**Comment by cp2004** [comment]
@DuschdrBabbe There's a release candidate available for 0.2.0rc1 if you want to give it a go. Feedback ticket #54.

**Comment by cp2004** [comment]
0.2.0 has been released
