### ISSUE TITLE
[Bug] Previous intensity values not honored when editing the config.

### ISSUE THREAD

**Issue by samwiseg0** [cp2004/OctoPrint-WLED#62]
**Description of the bug**

When editing printing effects. If you change the intensity, the changes do not persist if you load the config again or make any other changes after saving. This also changes any other effects that contained modified intensities back to 127.

**Steps to reproduce**

1. Open the config modal. 
2. Edit a printing effect
3. Change the intensity
4. Save
5. Attempt to edit the config again
6. Note that the intensity is back to default of 127.

**What did you expect to happen**

The intensity config to persist. 

**Logs and screenshots**

Does the plugin have its own logging? I did not see a specific log file for WLED?

![Screen Shot 2021-06-11 at 4 31 10 PM](https://user-images.githubusercontent.com/2241731/121746477-eee7a200-cad3-11eb-867a-0941b270274c.png)

**Version of plugin and OctoPrint**

Octorpint: 1.6.1
Plugin 0.2.0

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36

**Additional context**

N/A

**Comment by cp2004** [comment]
Try 0.2.1rc1 from the pre-release channel. Not entirely sure if I've done it right since tagging the right branch was hard, hopefully some git magic has sorted it.

> Does the plugin have its own logging? I did not see a specific log file for WLED?

There's no specific log, everything for this plugin is logged to the `octoprint.log`. And there can be quite a lot of detail/granular control as well (if you 
wanted it) using the debug logging settings:
![image](https://user-images.githubusercontent.com/31997505/121751489-24a57e80-cb06-11eb-8fa2-6c95148d4159.png)

**Comment by samwiseg0** [comment]
For some reason it is still not available? I told it to check for updates but it returns everything is up to date
![Screen Shot 2021-06-11 at 6 55 40 PM](https://user-images.githubusercontent.com/2241731/121755983-a5ed1900-cae6-11eb-8e59-4abe7ebd5f23.png)

> There's no specific log, everything for this plugin is logged to the octoprint.log. And there can be quite a lot of detail/granular control as well (if you

Ah ok I was not sure. Thanks

**Comment by samwiseg0** [comment]
I updated manually. Its fixed! Thanks!

**Comment by cp2004** [comment]
The manual install should work:

```
https://github.com/cp2004/OctoPrint-WLED/releases/download/0.2.1rc1/release.zip
```

The tag was initially created from the wrong branch, so I moved it across but I think I've confused GitHub so OctoPrint is not picking it up...
